export default [
    {
      'city': 'San Jose',
      'city_ascii': 'San Jose',
      'lat': 13.9397,
      'lng': -90.82,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Escuintla',
      'capital': '',
      'population': 18655,
      'id': 1320016478
    },
    {
      'city': 'Mazatenango',
      'city_ascii': 'Mazatenango',
      'lat': 14.5304,
      'lng': -91.51,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'SuchitepÃ©quez',
      'capital': 'admin',
      'population': 64652,
      'id': 1320123250
    },
    {
      'city': 'Cuilapa',
      'city_ascii': 'Cuilapa',
      'lat': 14.279,
      'lng': -90.298,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Santa Rosa',
      'capital': 'admin',
      'population': 16484,
      'id': 1320810416
    },
    {
      'city': 'CobÃ¡n',
      'city_ascii': 'Coban',
      'lat': 15.47,
      'lng': -90.38,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Alta Verapaz',
      'capital': 'admin',
      'population': 65194,
      'id': 1320020813
    },
    {
      'city': 'Jutiapa',
      'city_ascii': 'Jutiapa',
      'lat': 14.29,
      'lng': -89.9,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Jutiapa',
      'capital': 'admin',
      'population': 50681,
      'id': 1320264119
    },
    {
      'city': 'Retalhuleu',
      'city_ascii': 'Retalhuleu',
      'lat': 14.5371,
      'lng': -91.677,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Retalhuleu',
      'capital': 'admin',
      'population': 36656,
      'id': 1320999503
    },
    {
      'city': 'Livingston',
      'city_ascii': 'Livingston',
      'lat': 15.8307,
      'lng': -88.7562,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Izabal',
      'capital': 'minor',
      'population': 14350,
      'id': 1320970605
    },
    {
      'city': 'San Luis',
      'city_ascii': 'San Luis',
      'lat': 16.2,
      'lng': -89.44,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'PetÃ©n',
      'capital': 'minor',
      'population': 132470,
      'id': 1320642245
    },
    {
      'city': 'San Marcos',
      'city_ascii': 'San Marcos',
      'lat': 14.966,
      'lng': -91.8,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'San Marcos',
      'capital': 'admin',
      'population': 25088,
      'id': 1320960166
    },
    {
      'city': 'Flores',
      'city_ascii': 'Flores',
      'lat': 16.9337,
      'lng': -89.8833,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'PetÃ©n',
      'capital': 'admin',
      'population': 38035,
      'id': 1320651129
    },
    {
      'city': 'Escuintla',
      'city_ascii': 'Escuintla',
      'lat': 14.3004,
      'lng': -90.78,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Escuintla',
      'capital': 'admin',
      'population': 107638,
      'id': 1320838903
    },
    {
      'city': 'SalamÃ¡',
      'city_ascii': 'Salama',
      'lat': 15.103,
      'lng': -90.314,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Baja Verapaz',
      'capital': 'admin',
      'population': 40000,
      'id': 1320223205
    },
    {
      'city': 'Chiquimula',
      'city_ascii': 'Chiquimula',
      'lat': 14.797,
      'lng': -89.544,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Chiquimula',
      'capital': 'admin',
      'population': 41521,
      'id': 1320041079
    },
    {
      'city': 'Chimaltenango',
      'city_ascii': 'Chimaltenango',
      'lat': 14.662,
      'lng': -90.82,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Chimaltenango',
      'capital': 'admin',
      'population': 82370,
      'id': 1320147012
    },
    {
      'city': 'El Progreso',
      'city_ascii': 'El Progreso',
      'lat': 14.85,
      'lng': -90.0167,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'El Progreso',
      'capital': 'admin',
      'population': 147197,
      'id': 1320849830
    },
    {
      'city': 'Antigua Guatemala',
      'city_ascii': 'Antigua Guatemala',
      'lat': 14.5667,
      'lng': -90.7333,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'SacatepÃ©quez',
      'capital': 'admin',
      'population': 39368,
      'id': 1320020808
    },
    {
      'city': 'Jalapa',
      'city_ascii': 'Jalapa',
      'lat': 14.633,
      'lng': -89.989,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Jalapa',
      'capital': 'admin',
      'population': 45834,
      'id': 1320108089
    },
    {
      'city': 'Quetzaltenango',
      'city_ascii': 'Quetzaltenango',
      'lat': 14.83,
      'lng': -91.52,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Quetzaltenango',
      'capital': 'admin',
      'population': 575263,
      'id': 1320083599
    },
    {
      'city': 'Puerto Barrios',
      'city_ascii': 'Puerto Barrios',
      'lat': 15.7175,
      'lng': -88.5927,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Izabal',
      'capital': 'admin',
      'population': 56605,
      'id': 1320517532
    },
    {
      'city': 'TotonicapÃ¡n',
      'city_ascii': 'Totonicapan',
      'lat': 14.914,
      'lng': -91.358,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'TotonicapÃ¡n',
      'capital': 'admin',
      'population': 69734,
      'id': 1320223386
    },
    {
      'city': 'Zacapa',
      'city_ascii': 'Zacapa',
      'lat': 14.972,
      'lng': -89.529,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Zacapa',
      'capital': 'admin',
      'population': 36088,
      'id': 1320977472
    },
    {
      'city': 'SololÃ¡',
      'city_ascii': 'Solola',
      'lat': 14.773,
      'lng': -91.183,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'SololÃ¡',
      'capital': 'admin',
      'population': 45373,
      'id': 1320747500
    },
    {
      'city': 'Guatemala',
      'city_ascii': 'Guatemala',
      'lat': 14.6211,
      'lng': -90.527,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Guatemala',
      'capital': 'primary',
      'population': 1024000,
      'id': 1320197916
    },
    {
      'city': 'La Libertad',
      'city_ascii': 'La Libertad',
      'lat': 16.7804,
      'lng': -90.12,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'PetÃ©n',
      'capital': 'minor',
      'population': 8646,
      'id': 1320389989
    },
    {
      'city': 'Huehuetenango',
      'city_ascii': 'Huehuetenango',
      'lat': 15.3204,
      'lng': -91.47,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'Huehuetenango',
      'capital': 'admin',
      'population': 85992,
      'id': 1320742269
    },
    {
      'city': 'Santa Cruz Del Quiche',
      'city_ascii': 'Santa Cruz Del Quiche',
      'lat': 15.0333,
      'lng': -91.1333,
      'country': 'Guatemala',
      'iso2': 'GT',
      'iso3': 'GTM',
      'admin_name': 'QuichÃ©',
      'capital': 'admin',
      'population': 23618,
      'id': 1320642159
    },
    {
      'city': 'Tegucigalpa',
      'city_ascii': 'Tegucigalpa',
      'lat': 14.102,
      'lng': -87.2175,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Francisco MorazÃ¡n',
      'capital': 'primary',
      'population': 946000,
      'id': 1340344059
    },
    {
      'city': 'Yoro',
      'city_ascii': 'Yoro',
      'lat': 15.06,
      'lng': -87.29,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Yoro',
      'capital': '',
      'population': 15774,
      'id': 1340550354
    },
    {
      'city': 'Brus Laguna',
      'city_ascii': 'Brus Laguna',
      'lat': 15.7504,
      'lng': -84.48,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Gracias a Dios',
      'capital': '',
      'population': 4067,
      'id': 1340003428
    },
    {
      'city': 'La Ceiba',
      'city_ascii': 'La Ceiba',
      'lat': 15.7631,
      'lng': -86.797,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'AtlÃ¡ntida',
      'capital': 'admin',
      'population': 145926,
      'id': 1340870189
    },
    {
      'city': 'Choluteca',
      'city_ascii': 'Choluteca',
      'lat': 13.3007,
      'lng': -87.1908,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Choluteca',
      'capital': 'admin',
      'population': 99429,
      'id': 1340256619
    },
    {
      'city': 'Trujillo',
      'city_ascii': 'Trujillo',
      'lat': 15.9104,
      'lng': -85.96,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'ColÃ³n',
      'capital': 'admin',
      'population': 9646,
      'id': 1340756106
    },
    {
      'city': 'Comayagua',
      'city_ascii': 'Comayagua',
      'lat': 14.4604,
      'lng': -87.65,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Comayagua',
      'capital': 'admin',
      'population': 71142,
      'id': 1340015594
    },
    {
      'city': 'Santa Rosa de CopÃ¡n',
      'city_ascii': 'Santa Rosa de Copan',
      'lat': 14.77,
      'lng': -88.78,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'CopÃ¡n',
      'capital': 'admin',
      'population': 35529,
      'id': 1340050563
    },
    {
      'city': 'San Pedro Sula',
      'city_ascii': 'San Pedro Sula',
      'lat': 15.5,
      'lng': -88.03,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'CortÃ©s',
      'capital': 'admin',
      'population': 680091,
      'id': 1340568412
    },
    {
      'city': 'YuscarÃ¡n',
      'city_ascii': 'Yuscaran',
      'lat': 13.944,
      'lng': -86.851,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'El ParaÃ­so',
      'capital': 'admin',
      'population': 2371,
      'id': 1340315181
    },
    {
      'city': 'Puerto Lempira',
      'city_ascii': 'Puerto Lempira',
      'lat': 15.262,
      'lng': -83.7716,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Gracias a Dios',
      'capital': 'admin',
      'population': 4856,
      'id': 1340110055
    },
    {
      'city': 'La Esperanza',
      'city_ascii': 'La Esperanza',
      'lat': 14.333,
      'lng': -88.1667,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'IntibucÃ¡',
      'capital': 'admin',
      'population': 5318,
      'id': 1340614286
    },
    {
      'city': 'RoatÃ¡n',
      'city_ascii': 'Roatan',
      'lat': 16.33,
      'lng': -86.519,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Islas de la BahÃ­a',
      'capital': 'admin',
      'population': 7514,
      'id': 1340163370
    },
    {
      'city': 'La Paz',
      'city_ascii': 'La Paz',
      'lat': 14.32,
      'lng': -87.684,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'La Paz',
      'capital': 'admin',
      'population': 17555,
      'id': 1340290947
    },
    {
      'city': 'Gracias',
      'city_ascii': 'Gracias',
      'lat': 14.5833,
      'lng': -88.5833,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Lempira',
      'capital': 'admin',
      'population': 7909,
      'id': 1340141391
    },
    {
      'city': 'Nueva Ocotepeque',
      'city_ascii': 'Nueva Ocotepeque',
      'lat': 14.437,
      'lng': -89.182,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Ocotepeque',
      'capital': 'admin',
      'population': 8780,
      'id': 1340380637
    },
    {
      'city': 'Juticalpa',
      'city_ascii': 'Juticalpa',
      'lat': 14.6704,
      'lng': -86.23,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Olancho',
      'capital': 'admin',
      'population': 37442,
      'id': 1340411203
    },
    {
      'city': 'Santa BÃ¡rbara',
      'city_ascii': 'Santa Barbara',
      'lat': 14.919,
      'lng': -88.236,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Santa BÃ¡rbara',
      'capital': 'admin',
      'population': 15119,
      'id': 1340312026
    },
    {
      'city': 'Nacaome',
      'city_ascii': 'Nacaome',
      'lat': 13.53,
      'lng': -87.49,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Valle',
      'capital': 'admin',
      'population': 47000,
      'id': 1340964186
    },
    {
      'city': 'Yoro',
      'city_ascii': 'Yoro',
      'lat': 15.1375,
      'lng': -87.1278,
      'country': 'Honduras',
      'iso2': 'HN',
      'iso3': 'HND',
      'admin_name': 'Yoro',
      'capital': 'admin',
      'population': '',
      'id': 1340638121
    },
    {
      'city': 'San Salvador',
      'city_ascii': 'San Salvador',
      'lat': 13.71,
      'lng': -89.203,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'San Salvador',
      'capital': 'primary',
      'population': 1433000,
      'id': 1222647454
    },
    {
      'city': 'San Miguel',
      'city_ascii': 'San Miguel',
      'lat': 13.4833,
      'lng': -88.1833,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'San Miguel',
      'capital': 'admin',
      'population': 201563,
      'id': 1222009747
    },
    {
      'city': 'Nueva San Salvador',
      'city_ascii': 'Nueva San Salvador',
      'lat': 13.674,
      'lng': -89.29,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'La Libertad',
      'capital': 'admin',
      'population': 124694,
      'id': 1222613306
    },
    {
      'city': 'AhuachapÃ¡n',
      'city_ascii': 'Ahuachapan',
      'lat': 13.919,
      'lng': -89.845,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'AhuachapÃ¡n',
      'capital': 'admin',
      'population': 34102,
      'id': 1222480039
    },
    {
      'city': 'Cojutepeque',
      'city_ascii': 'Cojutepeque',
      'lat': 13.7167,
      'lng': -88.9333,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'CuscatlÃ¡n',
      'capital': 'admin',
      'population': 48411,
      'id': 1222979186
    },
    {
      'city': 'Zacatecoluca',
      'city_ascii': 'Zacatecoluca',
      'lat': 13.508,
      'lng': -88.868,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'La Paz',
      'capital': 'admin',
      'population': 39613,
      'id': 1222647953
    },
    {
      'city': 'La UniÃ³n',
      'city_ascii': 'La Union',
      'lat': 13.332,
      'lng': -87.839,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'La UniÃ³n',
      'capital': 'admin',
      'population': 26807,
      'id': 1222307415
    },
    {
      'city': 'San Francisco Gotera',
      'city_ascii': 'San Francisco Gotera',
      'lat': 13.7,
      'lng': -88.1,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'MorazÃ¡n',
      'capital': 'admin',
      'population': 16152,
      'id': 1222399599
    },
    {
      'city': 'Sensuntepeque',
      'city_ascii': 'Sensuntepeque',
      'lat': 13.88,
      'lng': -88.63,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'CabaÃ±as',
      'capital': 'admin',
      'population': 26989,
      'id': 1222098918
    },
    {
      'city': 'Chalatenango',
      'city_ascii': 'Chalatenango',
      'lat': 14.072,
      'lng': -89.094,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'Chalatenango',
      'capital': 'admin',
      'population': 29271,
      'id': 1222515741
    },
    {
      'city': 'Santa Ana',
      'city_ascii': 'Santa Ana',
      'lat': 13.9946,
      'lng': -89.5598,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'Santa Ana',
      'capital': 'admin',
      'population': 234478,
      'id': 1222021362
    },
    {
      'city': 'San Vicente',
      'city_ascii': 'San Vicente',
      'lat': 13.641,
      'lng': -88.785,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'San Vicente',
      'capital': 'admin',
      'population': 37326,
      'id': 1222913273
    },
    {
      'city': 'Sonsonate',
      'city_ascii': 'Sonsonate',
      'lat': 13.72,
      'lng': -89.73,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'Sonsonate',
      'capital': 'admin',
      'population': 168947,
      'id': 1222380208
    },
    {
      'city': 'UsulutÃ¡n',
      'city_ascii': 'Usulutan',
      'lat': 13.346,
      'lng': -88.432,
      'country': 'El Salvador',
      'iso2': 'SV',
      'iso3': 'SLV',
      'admin_name': 'UsulutÃ¡n',
      'capital': 'admin',
      'population': 51910,
      'id': 1222984157
    },
    {
      'city': 'Managua',
      'city_ascii': 'Managua',
      'lat': 12.153,
      'lng': -86.2685,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Managua',
      'capital': 'primary',
      'population': 920000,
      'id': 1558296252
    },
    {
      'city': 'San Juan de Nicaragua',
      'city_ascii': 'San Juan de Nicaragua',
      'lat': 10.9204,
      'lng': -83.7,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'RÃ­o San Juan',
      'capital': '',
      'population': 1000,
      'id': 1558125707
    },
    {
      'city': 'San Juan del Sur',
      'city_ascii': 'San Juan del Sur',
      'lat': 11.25,
      'lng': -85.86,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Rivas',
      'capital': '',
      'population': 7790,
      'id': 1558967577
    },
    {
      'city': 'San Carlos',
      'city_ascii': 'San Carlos',
      'lat': 11.2,
      'lng': -84.8333,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'RÃ­o San Juan',
      'capital': 'admin',
      'population': 13451,
      'id': 1558170572
    },
    {
      'city': 'Juigalpa',
      'city_ascii': 'Juigalpa',
      'lat': 12.11,
      'lng': -85.38,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Chontales',
      'capital': 'admin',
      'population': 54731,
      'id': 1558986603
    },
    {
      'city': 'Boaco',
      'city_ascii': 'Boaco',
      'lat': 12.47,
      'lng': -85.66,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Boaco',
      'capital': 'admin',
      'population': 29046,
      'id': 1558023610
    },
    {
      'city': 'Granadaâ€Ž',
      'city_ascii': 'Granada',
      'lat': 11.9337,
      'lng': -85.95,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Granada',
      'capital': 'admin',
      'population': 105219,
      'id': 1558101678
    },
    {
      'city': 'Puerto Cabezas',
      'city_ascii': 'Puerto Cabezas',
      'lat': 14.0333,
      'lng': -83.3834,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Caribe Norte',
      'capital': 'admin',
      'population': 43001,
      'id': 1558656214
    },
    {
      'city': 'Jinotepe',
      'city_ascii': 'Jinotepe',
      'lat': 11.846,
      'lng': -86.195,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Carazo',
      'capital': 'admin',
      'population': 29507,
      'id': 1558246417
    },
    {
      'city': 'Jinotega',
      'city_ascii': 'Jinotega',
      'lat': 13.091,
      'lng': -86,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Jinotega',
      'capital': 'admin',
      'population': 51073,
      'id': 1558697688
    },
    {
      'city': 'LeÃ³n',
      'city_ascii': 'Leon',
      'lat': 12.4356,
      'lng': -86.8794,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'LeÃ³n',
      'capital': 'admin',
      'population': 164441,
      'id': 1558654236
    },
    {
      'city': 'EstelÃ­',
      'city_ascii': 'Esteli',
      'lat': 13.09,
      'lng': -86.36,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'EstelÃ­',
      'capital': 'admin',
      'population': 107839,
      'id': 1558801854
    },
    {
      'city': 'Somoto',
      'city_ascii': 'Somoto',
      'lat': 13.476,
      'lng': -86.583,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Madriz',
      'capital': 'admin',
      'population': 20316,
      'id': 1558605178
    },
    {
      'city': 'Chinandega',
      'city_ascii': 'Chinandega',
      'lat': 12.6304,
      'lng': -87.13,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Chinandega',
      'capital': 'admin',
      'population': 139023,
      'id': 1558172276
    },
    {
      'city': 'Ocotal',
      'city_ascii': 'Ocotal',
      'lat': 13.63,
      'lng': -86.473,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Nueva Segovia',
      'capital': 'admin',
      'population': 33928,
      'id': 1558006000
    },
    {
      'city': 'Masaya',
      'city_ascii': 'Masaya',
      'lat': 11.969,
      'lng': -86.095,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Masaya',
      'capital': 'admin',
      'population': 130113,
      'id': 1558765329
    },
    {
      'city': 'Bluefields',
      'city_ascii': 'Bluefields',
      'lat': 12,
      'lng': -83.7649,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Caribe Sur',
      'capital': 'admin',
      'population': 44373,
      'id': 1558301368
    },
    {
      'city': 'Rivas',
      'city_ascii': 'Rivas',
      'lat': 11.4404,
      'lng': -85.82,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Rivas',
      'capital': 'admin',
      'population': 31941,
      'id': 1558146594
    },
    {
      'city': 'Matagalpa',
      'city_ascii': 'Matagalpa',
      'lat': 12.9171,
      'lng': -85.9167,
      'country': 'Nicaragua',
      'iso2': 'NI',
      'iso3': 'NIC',
      'admin_name': 'Matagalpa',
      'capital': 'admin',
      'population': 109089,
      'id': 1558728443
    },
    {
      'city': 'San JosÃ©',
      'city_ascii': 'San Jose',
      'lat': 9.935,
      'lng': -84.0841,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'San JosÃ©',
      'capital': 'primary',
      'population': 1284000,
      'id': 1188749877
    },
    {
      'city': 'Sixaola',
      'city_ascii': 'Sixaola',
      'lat': 9.5204,
      'lng': -82.62,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'LimÃ³n',
      'capital': '',
      'population': 1823,
      'id': 1188537249
    },
    {
      'city': 'Alajuela',
      'city_ascii': 'Alajuela',
      'lat': 10.02,
      'lng': -84.23,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Alajuela',
      'capital': 'admin',
      'population': 387743,
      'id': 1188394508
    },
    {
      'city': 'Canas',
      'city_ascii': 'Canas',
      'lat': 10.43,
      'lng': -85.1,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Guanacaste',
      'capital': '',
      'population': 20306,
      'id': 1188753368
    },
    {
      'city': 'La Cruz',
      'city_ascii': 'La Cruz',
      'lat': 11.0704,
      'lng': -85.63,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Guanacaste',
      'capital': '',
      'population': 4319,
      'id': 1188840021
    },
    {
      'city': 'Cartago',
      'city_ascii': 'Cartago',
      'lat': 9.87,
      'lng': -83.93,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Cartago',
      'capital': 'admin',
      'population': 196946,
      'id': 1188911724
    },
    {
      'city': 'Liberia',
      'city_ascii': 'Liberia',
      'lat': 10.6338,
      'lng': -85.4333,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Guanacaste',
      'capital': 'admin',
      'population': 45380,
      'id': 1188743090
    },
    {
      'city': 'Heredia',
      'city_ascii': 'Heredia',
      'lat': 9.992,
      'lng': -84.12,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Heredia',
      'capital': 'admin',
      'population': 21947,
      'id': 1188210837
    },
    {
      'city': 'Puerto Limon',
      'city_ascii': 'Puerto Limon',
      'lat': 10,
      'lng': -83.0333,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'LimÃ³n',
      'capital': 'admin',
      'population': 85001,
      'id': 1188214393
    },
    {
      'city': 'Ciudad Cortes',
      'city_ascii': 'Ciudad Cortes',
      'lat': 8.9604,
      'lng': -83.53,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Puntarenas',
      'capital': '',
      'population': 3850,
      'id': 1188296792
    },
    {
      'city': 'Golfito',
      'city_ascii': 'Golfito',
      'lat': 8.65,
      'lng': -83.15,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Puntarenas',
      'capital': '',
      'population': 6777,
      'id': 1188695145
    },
    {
      'city': 'Quesada',
      'city_ascii': 'Quesada',
      'lat': 10.3305,
      'lng': -84.44,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Alajuela',
      'capital': '',
      'population': 31106,
      'id': 1188199888
    },
    {
      'city': 'Puntarenas',
      'city_ascii': 'Puntarenas',
      'lat': 9.9702,
      'lng': -84.8336,
      'country': 'Costa Rica',
      'iso2': 'CR',
      'iso3': 'CRI',
      'admin_name': 'Puntarenas',
      'capital': 'admin',
      'population': 57102,
      'id': 1188639267
    },
    {
      'city': 'Balboa',
      'city_ascii': 'Balboa',
      'lat': 8.95,
      'lng': -79.5667,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'PanamÃ¡',
      'capital': '',
      'population': 62882,
      'id': 1591922184
    },
    {
      'city': 'Panama City',
      'city_ascii': 'Panama City',
      'lat': 8.968,
      'lng': -79.533,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'PanamÃ¡',
      'capital': 'primary',
      'population': 1281000,
      'id': 1591672475
    },
    {
      'city': 'La Chorrera',
      'city_ascii': 'La Chorrera',
      'lat': 8.8803,
      'lng': -79.7833,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'PanamÃ¡ Oeste',
      'capital': 'admin',
      'population': '',
      'id': 1591982720
    },
    {
      'city': 'ColÃ³n',
      'city_ascii': 'Colon',
      'lat': 9.365,
      'lng': -79.875,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'ColÃ³n',
      'capital': 'admin',
      'population': 204000,
      'id': 1591599922
    },
    {
      'city': 'JaquÃ©',
      'city_ascii': 'Jaque',
      'lat': 7.519,
      'lng': -78.166,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'DariÃ©n',
      'capital': 'minor',
      'population': 1357,
      'id': 1591579329
    },
    {
      'city': 'La Palma',
      'city_ascii': 'La Palma',
      'lat': 8.3982,
      'lng': -78.1402,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'DariÃ©n',
      'capital': 'admin',
      'population': 1845,
      'id': 1591177082
    },
    {
      'city': 'Penonome',
      'city_ascii': 'Penonome',
      'lat': 8.51,
      'lng': -80.36,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'CoclÃ©',
      'capital': 'admin',
      'population': 28766,
      'id': 1591602960
    },
    {
      'city': 'UniÃ³n ChocÃ³',
      'city_ascii': 'Union Choco',
      'lat': 8.0989,
      'lng': -77.6085,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'EmberÃ¡-Wounaan',
      'capital': 'admin',
      'population': '',
      'id': 1591671914
    },
    {
      'city': 'David',
      'city_ascii': 'David',
      'lat': 8.4333,
      'lng': -82.4333,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'ChiriquÃ­',
      'capital': 'admin',
      'population': 110037,
      'id': 1591487342
    },
    {
      'city': 'Puerto Armuelles',
      'city_ascii': 'Puerto Armuelles',
      'lat': 8.28,
      'lng': -82.87,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'ChiriquÃ­',
      'capital': 'minor',
      'population': 27147,
      'id': 1591562054
    },
    {
      'city': 'Santiago',
      'city_ascii': 'Santiago',
      'lat': 8.1004,
      'lng': -80.9833,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Veraguas',
      'capital': 'admin',
      'population': 45955,
      'id': 1591231138
    },
    {
      'city': 'Las Tablas',
      'city_ascii': 'Las Tablas',
      'lat': 7.7604,
      'lng': -80.28,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Los Santos',
      'capital': 'admin',
      'population': 11358,
      'id': 1591472114
    },
    {
      'city': 'ChitrÃ©',
      'city_ascii': 'Chitre',
      'lat': 7.97,
      'lng': -80.42,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Herrera',
      'capital': 'admin',
      'population': 44082,
      'id': 1591257375
    },
    {
      'city': 'Buabidi',
      'city_ascii': 'Buabidi',
      'lat': 8.4746,
      'lng': -81.6983,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'NgÃ¶be-BuglÃ©',
      'capital': 'admin',
      'population': '',
      'id': 1591495919
    },
    {
      'city': 'Bocas del Toro',
      'city_ascii': 'Bocas del Toro',
      'lat': 9.3354,
      'lng': -82.2475,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Bocas del Toro',
      'capital': 'admin',
      'population': 9883,
      'id': 1591037947
    },
    {
      'city': 'Almirante',
      'city_ascii': 'Almirante',
      'lat': 9.3,
      'lng': -82.4,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Bocas del Toro',
      'capital': 'minor',
      'population': 8114,
      'id': 1591293829
    },
    {
      'city': 'El Porvenir',
      'city_ascii': 'El Porvenir',
      'lat': 9.5417,
      'lng': -78.972,
      'country': 'Panama',
      'iso2': 'PA',
      'iso3': 'PAN',
      'admin_name': 'Kuna Yala',
      'capital': 'admin',
      'population': 10,
      'id': 1591425685
    }
  ]